# Basic
name: "Beagle Projects"

author:
  name: Elton Viana
  facebook: eltonsviana
  twitter: eltonsviana
  github: eltonvs
  linkedin: eltonviana
  email: me@eltonviana.com

# Google-analytics
google-analytics:
  id: ""

# Disqus
disqus:
  id: "beagleprojects"

# URL
baseurl: "/beagleproject"
url: "https://eltonviana.com"

timezone: America/Sao_Paulo
permalink: /blog/:title/

# Pagination
paginate: 3
paginate_path: /page/:num/

# Markdown
markdown: kramdown
kramdown:
  imput: GFM

# Navigation
nav:
  - name: "About"
    url: "/about"
  - name: "Archive"
    url: "/archive"
  - name: "Tags"
    url: "/tags"
  - name: "Github"
    url: "https://github.com/eltonvs/beagleproject"

# Sass
sass:
  sass_dir: _sass
  style: :compressed

# Scopes
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
gems:
  - jekyll-seo-tag
  - jekyll-paginate

exclude: [vendor]
